### ISSUE TITLE
Interest in GSOC Projects

### ISSUE THREAD

**Issue by connorcartwright** [Greennav/greennav.github.io#12]
Hey guys @maxlorenz @maxlorenz @fabianbormann :bowtie:

I am very interested in a couple of the projects you've got going, specifically the Visualization tool and the Prototyping tool projects.

I'm from the United Kingdom currently on my industrial placement year at [Smartzer](http://www.smartzer.com). I studied at Aston University in my first year (and achieved the highest grades out of all first year CS students) before transferring to the University of Birmingham.

I gained a lot of experience programming in Java whilst at uni, and during the past 8 months I have primarily been helping to design and then programming front-end systems in JavaScript, JQuery, CSS and HTML. We're about to start re-implementing our systems using React for the front end.

Recently my team won 2nd place at a hackathon where I used Node.js and Socket.io and my teammate worked on the front-end to create a chatroom system with the idea of bringing all university systems (email, chat, assignments, exams, calendar, timetable, etc.) into one easy to use dashboard.

I would be very happy to discuss the projects and to discuss whether I'd be a suitable fit before submitting my proposal.

I hope you're having a great weekend!

Cheers,
Connor

**Comment by fabianbormann** [comment]
Hi @ConnorCartwright, 

very cool that you are interested in the GreenNav front-end projects! 
It would be great if you check out our [G+ page](https://plus.google.com/communities/110704433153909631379) or [Google Groups](https://groups.google.com/forum/#!forum/greennav). Maybe there is an existing answer that matches with one of your questions. 
If you have a question about the code, errors, enhancements, feature requests, etc. (independent of GSoC) you could write your question as an issue in the related repository. But if you want to get more formal/informal information about the GSoC projects please use G+ or google-groups.

Hope to see your proposal! Have a nice day! :)

Cheers,
Fabian
