### ISSUE TITLE
Easier workflow to make changes

### ISSUE THREAD

**Issue by tom3012** [Greennav/greennav.github.io#18]
To make changes and add new pages we need an easier workflow! Maybe we could use scripts instead of moving content manually to master branch. This would also be a more safe!

**Comment by maxlorenz** [comment]
The new README has two commands for launching the dev environment as well as a build command. We should deploy a simple shell script that checks out the source branch, hosts the dev container and builds in the right branch

**Comment by KyleAMathews** [comment]
I'd recommend https://www.netlify.com/ — they're free for open source sites *and* they auto-build and auto-deploy from github. No more worrying about rebuilding the site before something is live! Just click merge on a PR and the change will be deployed.

**Comment by maxlorenz** [comment]
Wow _very_ cool!

**Comment by tom3012** [comment]
Thanks to @KyleAMathews recommendation we are now able to build the documentation automatically with [netlify](https://www.netlify.com).

**Comment by KyleAMathews** [comment]
Cool!
