### ISSUE TITLE
Added midterm photo

### ISSUE THREAD

**Issue by AngelinaGevenko** [Greennav/greennav.github.io#29]
<img width="1188" alt="screen shot 2017-07-24 at 11 56 18 am" src="https://user-images.githubusercontent.com/25430929/28843971-6f39fb52-7703-11e7-8c1b-b880176dc697.png">

**Comment by tom3012** [comment]
Hi Angelina! Can this be closed?

**Comment by AngelinaGevenko** [comment]
Yes, can be closed
