### ISSUE TITLE
Add links to the terms in documentation

### ISSUE THREAD

**Issue by sitaramshelke** [Greennav/greennav.github.io#8]
Direct links to the terms like openstreetmap or weather services in [Database Service](https://github.com/Greennav/greennav.github.io/blob/master/wiki/Project-Ideas/Project-Ideas.md#database-service), [Vision](https://github.com/Greennav/greennav.github.io/blob/master/wiki/Roadmap.md#vision) and whatever looks specific, can be added so that students can check exactly which APIs are going tp be needed.

**Comment by maxlorenz** [comment]
We will create the corresponding repositories and create READMEs there. Thanks for your feedback!
